import "~/styles/globals.css";

// import { GeistSans } from "geist/font/sans"; // old default
import { Noto_Sans_JP } from "next/font/google";
import { type Metadata } from "next";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const notoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-noto-sans", // 
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className={`${notoSansJP.variable}`}>
      <body>{children}</body>
    </html>
  );
}
